on:
  push:
  workflow_dispatch:

jobs:
  helloworld:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Lecture CICD"
      - name: Get the present working directory
        run: pwd
      
      - name: list all the files
        run: ls

