on:
  push:
  workflow_dispatch:

jobs:
  helloworld:
    runs-on: ubuntu-latest
    steps:
      - name: Get a clone of the current repository
        uses: actions/checkout@v4

      - name: list all the files
        run: ls

